2023-07-29 16:25:38.276 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-29 16:25:38.276 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration snooz which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-29 16:25:38.277 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dreo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-29 16:25:39.025 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2023-07-29 16:25:39.044 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=55 from 2023-07-29 23:09:31.226161)
2023-07-29 16:25:43.627 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Franâ€™s Roku Streambar' for roku integration not ready yet: Invalid response from API: Error occurred while communicating with device; Retrying in background
2023-07-29 16:49:51.252 ERROR (SyncWorker_1) [roombapy.remote_client] Can't connect to 192.168.0.212, error: [Errno 111] Connection refused
2023-07-29 16:49:51.263 ERROR (SyncWorker_1) [roombapy.remote_client] Can't connect to 192.168.0.212, error: [Errno 111] Connection refused
2023-07-29 16:49:51.267 ERROR (SyncWorker_1) [roombapy.remote_client] Can't connect to 192.168.0.212, error: [Errno 111] Connection refused
2023-07-29 16:49:51.269 ERROR (SyncWorker_1) [roombapy.remote_client] Unable to connect to 192.168.0.212
2023-07-29 16:49:51.270 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Roomba' for roomba integration not ready yet; Retrying in background
2023-07-29 16:49:51.458 ERROR (roombapy) [roombapy.remote_client] Can't connect to 192.168.0.212, error: [Errno 111] Connection refused
2023-07-29 16:49:51.461 ERROR (roombapy) [roombapy.remote_client] Can't connect to 192.168.0.212, error: [Errno 111] Connection refused
2023-07-29 16:49:51.465 ERROR (roombapy) [roombapy.remote_client] Can't connect to 192.168.0.212, error: [Errno 111] Connection refused
2023-07-29 16:49:51.465 ERROR (roombapy) [roombapy.remote_client] Unable to connect to 192.168.0.212
2023-07-29 16:49:51.466 WARNING (roombapy) [roombapy.roomba] Unexpectedly disconnected from Roomba 192.168.0.212, code Unable to connect to Roomba at 192.168.0.212
2023-07-29 16:50:09.607 ERROR (SyncWorker_8) [roombapy.remote_client] Can't connect to 192.168.0.114, error: [Errno 111] Connection refused
2023-07-29 16:50:09.613 ERROR (SyncWorker_8) [roombapy.remote_client] Can't connect to 192.168.0.114, error: [Errno 111] Connection refused
2023-07-29 16:50:09.618 ERROR (SyncWorker_8) [roombapy.remote_client] Can't connect to 192.168.0.114, error: [Errno 111] Connection refused
2023-07-29 16:50:09.619 ERROR (SyncWorker_8) [roombapy.remote_client] Unable to connect to 192.168.0.114
2023-07-29 16:50:09.620 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Braava jet' for roomba integration not ready yet; Retrying in background
2023-07-29 16:50:10.221 ERROR (Recorder) [homeassistant] Error doing job: Unclosed connection
2023-07-29 16:50:45.706 WARNING (MainThread) [zigpy_deconz.api] No response to 'Command.aps_data_indication' command with seq id '0x54'
